<?php
/**
 * @file
 * Code for the Bootstrap Jumbotron module
 */

include_once 'hot_banner.features.inc';

/**
 * Implementation of hook_entity_info_alter()
 */
function hot_banner_entity_info_alter(&$entity_info) {
  // Fieldable panel pane bundle to for Bootstrap Jumbotron
  $entity_info['fieldable_panels_pane']['bundles']['hot_banner'] = array(
    'label' => t('Banner'),
    'pane category' => t('HotWidgets!'),
    'pane top level' => FALSE,
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      'real path' => 'admin/structure/fieldable-panels-panes/manage/hot-banner',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
}
/**
 * Implements hook_preprocess_fieldable_panels_pane().
 */

function hot_banner_preprocess_fieldable_panels_pane(&$variables){
  if($variables['elements']['#bundle'] === 'hot_banner'){
    $title = $variables['elements']['#fieldable_panels_pane']->title;
    $variables['attributes_array']['class'][] = 'banner';
    if(isset($variables['field_basic_url'])){
      $url = $variables['elements']['field_basic_url']['#items'][0]['url'];
      $variables['url'] = $url;
      $title = l($title, $url, array('attributes'=>array('title'=> $title)));
    }
    if(isset($variables['field_hot_styles'])){
      $variables['attributes_array']['class'][] =
         'banner-' . $variables['field_hot_styles'][0]['value'];
    }
    dpm($variables);
    $variables['elements']['title'] = array(
      '#theme' => 'html_tag',
      '#tag' => 'h1',
      '#value' => $title
    );

  }
}
/**
 * Implements hook_preprocess_panels_pane().
 */
function hot_banner_preprocess_panels_pane(&$variables){
  if(isset($variables['content']['#bundle']) && $variables['content']['#bundle']==='hot_banner' ){
    $variables['title'] = '';
  }
}

/**
 * Implements hook_theme().
 */
function hot_banner_theme(){
  return array(
    'fieldable_panels_pane__hot_banner' => array(
      'template' => 'templates/fieldable-panels-pane--hot-banner',
      'render element' => 'elements',
      'type' => 'module'
    )
  );
}
